# Generated by Django 4.1 on 2022-08-11 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expiracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_geral', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('r_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('r_semanal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('r_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
