# Generated by Django 4.1 on 2022-08-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_chave_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paridade', models.CharField(max_length=7)),
                ('call', models.CharField(blank=True, max_length=10, null=True)),
                ('put', models.CharField(blank=True, max_length=10, null=True)),
                ('payout', models.IntegerField()),
                ('analise', models.BooleanField(default=False)),
            ],
        ),
    ]
